module axilt_interconnect_wrapper #(
    parameter DATA_WIDTH = 32,
    parameter ADDR_WIDTH = 32,
    parameter STRB_WIDTH = DATA_WIDTH/8,
    parameter N_MASTERS  = 2,
    parameter N_SLAVES   = 3,

    parameter [ADDR_WIDTH-1:0] MEM_BASE_0 = 32'h80000000,
    parameter [ADDR_WIDTH-1:0] MEM_SIZE_0 = 32'h10000000,
    parameter [ADDR_WIDTH-1:0] MEM_BASE_1 = 32'h90000000,
    parameter [ADDR_WIDTH-1:0] MEM_SIZE_1 = 32'h10000000,
    parameter [ADDR_WIDTH-1:0] MEM_BASE_2 = 32'hA0000000,
    parameter [ADDR_WIDTH-1:0] MEM_SIZE_2 = 32'h10000000
) (

    input  i_RST,
    input  i_CLK,

    input  [ADDR_WIDTH-1:0] i_s_AWADDR_0,
    input  [0:0] i_s_AWVALID_0,
    output logic [0:0] o_s_AWREADY_0,
    input  [DATA_WIDTH-1:0] i_s_WDATA_0,
    input  [STRB_WIDTH-1:0] i_s_WSTRB_0,
    input  [0:0] i_s_WVALID_0,
    output logic [0:0] o_s_WREADY_0,
    output logic [1:0] o_s_BRESP_0,
    output logic [0:0] o_s_BVALID_0,
    input  [0:0] i_s_BREADY_0,
    input  [ADDR_WIDTH-1:0] i_s_ARADDR_0,
    input  [0:0] i_s_ARVALID_0,
    output logic [0:0] o_s_ARREADY_0,
    output logic [DATA_WIDTH-1:0] o_s_RDATA_0,
    output logic [1:0] o_s_RRESP_0,
    output logic [0:0] o_s_RVALID_0,
    input  [0:0] i_s_RREADY_0,

    input  [ADDR_WIDTH-1:0] i_s_AWADDR_1,
    input  [0:0] i_s_AWVALID_1,
    output logic [0:0] o_s_AWREADY_1,
    input  [DATA_WIDTH-1:0] i_s_WDATA_1,
    input  [STRB_WIDTH-1:0] i_s_WSTRB_1,
    input  [0:0] i_s_WVALID_1,
    output logic [0:0] o_s_WREADY_1,
    output logic [1:0] o_s_BRESP_1,
    output logic [0:0] o_s_BVALID_1,
    input  [0:0] i_s_BREADY_1,
    input  [ADDR_WIDTH-1:0] i_s_ARADDR_1,
    input  [0:0] i_s_ARVALID_1,
    output logic [0:0] o_s_ARREADY_1,
    output logic [DATA_WIDTH-1:0] o_s_RDATA_1,
    output logic [1:0] o_s_RRESP_1,
    output logic [0:0] o_s_RVALID_1,
    input  [0:0] i_s_RREADY_1,

    output logic [ADDR_WIDTH-1:0] o_m_AWADDR_0,
    output logic [0:0] o_m_AWVALID_0,
    input  [0:0] i_m_AWREADY_0,
    output logic [DATA_WIDTH-1:0] o_m_WDATA_0,
    output logic [STRB_WIDTH-1:0] o_m_WSTRB_0,
    output logic [0:0] o_m_WVALID_0,
    input  [0:0] i_m_WREADY_0,
    input  [1:0] i_m_BRESP_0,
    input  [0:0] i_m_BVALID_0,
    output logic [0:0] o_m_BREADY_0,
    output logic [ADDR_WIDTH-1:0] o_m_ARADDR_0,
    output logic [0:0] o_m_ARVALID_0,
    input  [0:0] i_m_ARREADY_0,
    input  [DATA_WIDTH-1:0] i_m_RDATA_0,
    input  [1:0] i_m_RRESP_0,
    input  [0:0] i_m_RVALID_0,
    output logic [0:0] o_m_RREADY_0,

    output logic [ADDR_WIDTH-1:0] o_m_AWADDR_1,
    output logic [0:0] o_m_AWVALID_1,
    input  [0:0] i_m_AWREADY_1,
    output logic [DATA_WIDTH-1:0] o_m_WDATA_1,
    output logic [STRB_WIDTH-1:0] o_m_WSTRB_1,
    output logic [0:0] o_m_WVALID_1,
    input  [0:0] i_m_WREADY_1,
    input  [1:0] i_m_BRESP_1,
    input  [0:0] i_m_BVALID_1,
    output logic [0:0] o_m_BREADY_1,
    output logic [ADDR_WIDTH-1:0] o_m_ARADDR_1,
    output logic [0:0] o_m_ARVALID_1,
    input  [0:0] i_m_ARREADY_1,
    input  [DATA_WIDTH-1:0] i_m_RDATA_1,
    input  [1:0] i_m_RRESP_1,
    input  [0:0] i_m_RVALID_1,
    output logic [0:0] o_m_RREADY_1,

    output logic [ADDR_WIDTH-1:0] o_m_AWADDR_2,
    output logic [0:0] o_m_AWVALID_2,
    input  [0:0] i_m_AWREADY_2,
    output logic [DATA_WIDTH-1:0] o_m_WDATA_2,
    output logic [STRB_WIDTH-1:0] o_m_WSTRB_2,
    output logic [0:0] o_m_WVALID_2,
    input  [0:0] i_m_WREADY_2,
    input  [1:0] i_m_BRESP_2,
    input  [0:0] i_m_BVALID_2,
    output logic [0:0] o_m_BREADY_2,
    output logic [ADDR_WIDTH-1:0] o_m_ARADDR_2,
    output logic [0:0] o_m_ARVALID_2,
    input  [0:0] i_m_ARREADY_2,
    input  [DATA_WIDTH-1:0] i_m_RDATA_2,
    input  [1:0] i_m_RRESP_2,
    input  [0:0] i_m_RVALID_2,
    output logic [0:0] o_m_RREADY_2
);

axilt_interconnect #(
    .DATA_WIDTH(DATA_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH),
    .STRB_WIDTH(STRB_WIDTH),
    .N_MASTERS(N_MASTERS),
    .N_SLAVES(N_SLAVES),
    .MEM_BASE_0(MEM_BASE_0), .MEM_SIZE_0(MEM_SIZE_0),
    .MEM_BASE_1(MEM_BASE_1), .MEM_SIZE_1(MEM_SIZE_1),
    .MEM_BASE_2(MEM_BASE_2), .MEM_SIZE_2(MEM_SIZE_2)
) axilt_ic (
    .i_RST(i_RST),
    .i_CLK(i_CLK),

    .i_s_AWADDR({i_s_AWADDR_1, i_s_AWADDR_0}),
    .i_s_AWVALID({i_s_AWVALID_1, i_s_AWVALID_0}),
    .o_s_AWREADY({o_s_AWREADY_1, o_s_AWREADY_0}),
    .i_s_WDATA({i_s_WDATA_1, i_s_WDATA_0}),
    .i_s_WSTRB({i_s_WSTRB_1, i_s_WSTRB_0}),
    .i_s_WVALID({i_s_WVALID_1, i_s_WVALID_0}),
    .o_s_WREADY({o_s_WREADY_1, o_s_WREADY_0}),
    .o_s_BRESP({o_s_BRESP_1, o_s_BRESP_0}),
    .o_s_BVALID({o_s_BVALID_1, o_s_BVALID_0}),
    .i_s_BREADY({i_s_BREADY_1, i_s_BREADY_0}),
    .i_s_ARADDR({i_s_ARADDR_1, i_s_ARADDR_0}),
    .i_s_ARVALID({i_s_ARVALID_1, i_s_ARVALID_0}),
    .o_s_ARREADY({o_s_ARREADY_1, o_s_ARREADY_0}),
    .o_s_RDATA({o_s_RDATA_1, o_s_RDATA_0}),
    .o_s_RRESP({o_s_RRESP_1, o_s_RRESP_0}),
    .o_s_RVALID({o_s_RVALID_1, o_s_RVALID_0}),
    .i_s_RREADY({i_s_RREADY_1, i_s_RREADY_0}),

    .o_m_AWADDR({o_m_AWADDR_2, o_m_AWADDR_1, o_m_AWADDR_0}),
    .o_m_AWVALID({o_m_AWVALID_2, o_m_AWVALID_1, o_m_AWVALID_0}),
    .i_m_AWREADY({i_m_AWREADY_2, i_m_AWREADY_1, i_m_AWREADY_0}),
    .o_m_WDATA({o_m_WDATA_2, o_m_WDATA_1, o_m_WDATA_0}),
    .o_m_WSTRB({o_m_WSTRB_2, o_m_WSTRB_1, o_m_WSTRB_0}),
    .o_m_WVALID({o_m_WVALID_2, o_m_WVALID_1, o_m_WVALID_0}),
    .i_m_WREADY({i_m_WREADY_2, i_m_WREADY_1, i_m_WREADY_0}),
    .i_m_BRESP({i_m_BRESP_2, i_m_BRESP_1, i_m_BRESP_0}),
    .i_m_BVALID({i_m_BVALID_2, i_m_BVALID_1, i_m_BVALID_0}),
    .o_m_BREADY({o_m_BREADY_2, o_m_BREADY_1, o_m_BREADY_0}),
    .o_m_ARADDR({o_m_ARADDR_2, o_m_ARADDR_1, o_m_ARADDR_0}),
    .o_m_ARVALID({o_m_ARVALID_2, o_m_ARVALID_1, o_m_ARVALID_0}),
    .i_m_ARREADY({i_m_ARREADY_2, i_m_ARREADY_1, i_m_ARREADY_0}),
    .i_m_RDATA({i_m_RDATA_2, i_m_RDATA_1, i_m_RDATA_0}),
    .i_m_RRESP({i_m_RRESP_2, i_m_RRESP_1, i_m_RRESP_0}),
    .i_m_RVALID({i_m_RVALID_2, i_m_RVALID_1, i_m_RVALID_0}),
    .o_m_RREADY({o_m_RREADY_2, o_m_RREADY_1, o_m_RREADY_0})
);

endmodule
